### ISSUE TITLE
Corrections `enabled` appears to create phase discontinuities at burst boundaries

### ISSUE THREAD

**Issue by scottstanie** [opera-adt/COMPASS#100]
I posted initial interferogram in #99 , but repeating after running the with/without test:

![image](https://user-images.githubusercontent.com/8291800/222310990-98a985fb-0bd8-4cce-8705-b9f3821f1d3b.png)

The top was run with corrections `enabled=True`, the default, and the bottom set `enabled=False`.
This discontinuity is across multiple subswaths (heres further to the right):
![image](https://user-images.githubusercontent.com/8291800/222311265-e6855438-9c23-4935-806b-054d63f3da02.png)

If you wanted to test, the top and bottom are

`/home/staniewi/dev/sweets-testing/bigger-area/interferograms/stitched/20200529_20200604.int`
`/home/staniewi/dev/sweets-testing/bigger-area-no-corrections//interferograms/stitched/20200529_20200604.int`

I was using the branch on #99 for this (same as main COMPASS except for s1_geocode_stack.py), with latest developement version of isce3. To generate them, I did `sweets --bbox -119.2 34.1 -117 35.5 --start "2020-05-29"  --end "2020-06-6" --track 71`

**Comment by scottstanie** [comment]
To answer @hfattahi 's question: I don't think this is at the frame boundary actually.

<img width="838" alt="image" src="https://user-images.githubusercontent.com/8291800/222531569-7e78b3cd-b0b8-4820-8680-e5aa7af64eae.png">

```python
import s1reader
s1zips = sorted(Path("/home/staniewi/dev/sweets-testing/data").glob("*0529*.zip"))
bursts1 = s1reader.load_bursts(s1zips[0], None, 3)
bursts2 = s1reader.load_bursts(s1zips[1], None, 3)
print(bursts1)
print(bursts2)

[
    Sentinel1BurstSlc(burst_id=t071_151215_iw3),
    Sentinel1BurstSlc(burst_id=t071_151216_iw3),
    Sentinel1BurstSlc(burst_id=t071_151217_iw3),
    Sentinel1BurstSlc(burst_id=t071_151218_iw3),
    Sentinel1BurstSlc(burst_id=t071_151219_iw3),
    Sentinel1BurstSlc(burst_id=t071_151220_iw3),
    Sentinel1BurstSlc(burst_id=t071_151221_iw3),
    Sentinel1BurstSlc(burst_id=t071_151222_iw3),
    Sentinel1BurstSlc(burst_id=t071_151223_iw3)
]

[
    Sentinel1BurstSlc(burst_id=t071_151224_iw3),
    Sentinel1BurstSlc(burst_id=t071_151225_iw3),
    Sentinel1BurstSlc(burst_id=t071_151226_iw3),
    Sentinel1BurstSlc(burst_id=t071_151227_iw3),
    Sentinel1BurstSlc(burst_id=t071_151228_iw3),
    Sentinel1BurstSlc(burst_id=t071_151229_iw3),
    Sentinel1BurstSlc(burst_id=t071_151230_iw3),
    Sentinel1BurstSlc(burst_id=t071_151231_iw3),
    Sentinel1BurstSlc(burst_id=t071_151232_iw3)
]

The top frame has bursts up to `151223`. It looks like the worst discontinuity is between `151224` and `151225`, and it likely the corrections applied to `t071_151225_iw3`.

```

**Comment by scottstanie** [comment]
oh @hfattahi it turns out I was wrong and your guess was right: that big discontinuity actually is at a frame boundary, but it's just a frame boundary at the 2nd date only (not the first)

```

In [12]: s1zips = sorted(Path("/home/staniewi/dev/sweets-testing/data").glob("*0604*.zip"))
    ...: bursts1 = s1reader.load_bursts(s1zips[0], None, 3)
    ...: bursts2 = s1reader.load_bursts(s1zips[1], None, 3)
    ...: print(bursts1)
    ...: print(bursts2)
[
    Sentinel1BurstSlc(burst_id=t071_151217_iw3),
    Sentinel1BurstSlc(burst_id=t071_151218_iw3),
    Sentinel1BurstSlc(burst_id=t071_151219_iw3),
    Sentinel1BurstSlc(burst_id=t071_151220_iw3),
    Sentinel1BurstSlc(burst_id=t071_151221_iw3),
    Sentinel1BurstSlc(burst_id=t071_151222_iw3),
    Sentinel1BurstSlc(burst_id=t071_151223_iw3),
    Sentinel1BurstSlc(burst_id=t071_151224_iw3),
    Sentinel1BurstSlc(burst_id=t071_151225_iw3)
]
[
    Sentinel1BurstSlc(burst_id=t071_151226_iw3),
    Sentinel1BurstSlc(burst_id=t071_151227_iw3),
    Sentinel1BurstSlc(burst_id=t071_151228_iw3),
    Sentinel1BurstSlc(burst_id=t071_151229_iw3),
    Sentinel1BurstSlc(burst_id=t071_151230_iw3),
    Sentinel1BurstSlc(burst_id=t071_151231_iw3),
    Sentinel1BurstSlc(burst_id=t071_151232_iw3),
    Sentinel1BurstSlc(burst_id=t071_151233_iw3),
    Sentinel1BurstSlc(burst_id=t071_151234_iw3)
]
```

from burst number "...25" to "...26" does happen between s1 granules on June 4th

**Comment by hfattahi** [comment]
Thanks @scottstanie. This is great. Since you have the data would you please print out the `burst.iw2_mid_range`?

**Comment by scottstanie** [comment]
looking at the labelled picture from the first comment, that feature is between `['t071_151225_iw3', 't071_151226_iw3']`

```python
bids = ['t071_151225_iw3', 't071_151226_iw3']
safes = sorted(glob.glob("/u/aurora-r0/staniewi/dev/sweets-testing/bigger-area-test-half0/data/*.SAFE"))
orbits = [s1reader.get_orbit_file_from_dir(f, orbit_dir="/home/staniewi/dev/orbits/") for f in safes]
bursts = [s1reader.load_bursts(f, o, 3, burst_ids=bids) for f, o in zip(safes, orbits)]
[b.iw2_mid_range for b in itertools.chain.from_iterable(bursts)]
#  Out[19]: [875604.926001518, 875604.926001518, 875284.1711161041, 875284.1711161041]
```

**Comment by scottstanie** [comment]
My mistake- the problem was `azimuth_fm_rate`
![image](https://user-images.githubusercontent.com/8291800/232905410-66e049f8-55bd-45e9-b0fe-9ec34d800f38.png)

that's the result with only the `azimuth_fm_rate` correction turned on
```
      correction_luts:
        azimuth_fm_rate: true
        bistatic_delay: false
        geometry_steering_doppler: false
        ionosphere_tec: false
        solid_earth_tides: false
        static_troposphere: false
        weather_model_troposphere:
          delay_type: wet_dry
          enabled: false
```

**Comment by scottstanie** [comment]
Sure thing, you can check with `sweets` if you wanted to browse yourself in jupyter
```
import sweets.plotting
sweets.plotting.browse_ifgs("/home/staniewi/dev/sweets-testing/bigger-area-test-azfmrate")
```
it's also in the other bursts it looks like

![image](https://user-images.githubusercontent.com/8291800/232909921-e1194e0e-1ec6-4db0-9ef6-22ae93823984.png)

going from iw3 to iw2 you can still see it:
![image](https://user-images.githubusercontent.com/8291800/232910146-72a3932e-d0c0-4c8c-84d7-1ea91d2a181e.png)

but iw1 looks much fainter
![image](https://user-images.githubusercontent.com/8291800/232910297-db4da7c3-505b-4838-97c7-8c33ce8f9f97.png)


it's really just this one line, I think where the frame boundary is on one day (though it's shifted by a burst on the other)

**Comment by vbrancat** [comment]
@scottstanie would you mind retesting this the latest version (main branch) of `COMPASS` and `s1-reader`?

**Comment by scottstanie** [comment]
I think it looks the same, were there any changes to the azimuth fm rate that might have fixed it?
![image](https://github.com/opera-adt/COMPASS/assets/8291800/9a92a077-93e8-4f2e-9c32-e420a67ded5a)

**Comment by seongsujeong** [comment]
Thanks @scottstanie for re-doing the test. We wanted to check if the PR #113 in `s1-reader` [here](https://github.com/opera-adt/s1-reader/pull/113) is related to the frame discontinuity reported here.
