### ISSUE TITLE
Few reminders and TODOs for finalization of LUT correction

### ISSUE THREAD

**Issue by seongsujeong** [opera-adt/COMPASS#106]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

This is a reminder to keep track of few items to be addressed when finalizing the LUT implementation

- [ ] Determine the order of correction layers to be written into output HDF5 file
- [ ] Decide the default behavior when LUT correction is enabled but TEC file is not provided in runconfig
  - take the comment [here](https://github.com/opera-adt/COMPASS/pull/102#discussion_r1134516481) into account

### Describe the feature request

I need or want [...]

**Comment by vbrancat** [comment]
Closing as it has been addressed by PR merged for Cal/Val.
