### ISSUE TITLE
Doc requirements file may need pinned versions to work

### ISSUE THREAD

**Issue by scottstanie** [opera-adt/COMPASS#153]
https://readthedocs.org/projects/opera-compass/builds/20747385/ failed from a likely timeout during environment solving.

https://github.com/readthedocs/readthedocs.org/issues/6692 and https://github.com/xarray-contrib/xarray-simlab/pull/105 and others have run into it and seem to solve the problem by pinning versions.

Also, I noticed that isce3 isn't on there since it wasn't in the requirements.txt, the the PR to solve it should add that.

**Comment by vbrancat** [comment]
@scottstanie can we get this resolved?

**Comment by scottstanie** [comment]
I've been waiting for one more approval on #170 which I believe resolves this
