### ISSUE TITLE
Azimuth SET LUT

### ISSUE THREAD

**Issue by seongsujeong** [opera-adt/COMPASS#159]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

Currently azimuth component of the SET was not being added into `az_lut_data` [here](https://github.com/opera-adt/COMPASS/blob/7ffab310ff1c1978ebd7d5507266e021d889ba03/src/compass/utils/lut.py#LL84C8-L84C8). This will be tested by more data / cases, and will be fixed.

### Describe the feature request

I need or want [...]

**Comment by vbrancat** [comment]
Closing this issue as we decided not to add the azimuth component of SET tides to the azimuth correction LUT. Analyses show that the improvement in absolute geolocation  is minimal
