### ISSUE TITLE
LUTs to convert DN to sigma0, beta0 gamma and noise correction

### ISSUE THREAD

**Issue by hfattahi** [opera-adt/COMPASS#17]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

ESA Sentinel-1 SLCs are provided in DNs and they can be converted to beta0, sigma0 or gamma and they can be corrected for the noise power. The conversion is done using LUTs provided with the SLC products. The OPERA CSLC products should have the same functionality, i.e., the LUTs should be carried to the grid of cslc (geo for geocoded slc). 

### Describe the feature request

The csls workflow (primarily the gslc workflow) should provide LUTs that users can use to get the conversion factors to convert DNs to beta0, sigma0 or gamma and the LUT for noise power should be also provided so that the noise can be removed if the users of gslc want to. This functionality can be only developed after [this issue](https://github.com/opera-adt/s1-reader/issues/27) on sentinel-1 reader is closed.

**Comment by vbrancat** [comment]
This issue has been resolved with in the latest cal/val delivery in the PR geocoding the calibration and noise  LUTs.
