### ISSUE TITLE
heading angle in the static layer

### ISSUE THREAD

**Issue by hfattahi** [opera-adt/COMPASS#171]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

One layer of the static layer is heading angle. The values of the dataset for an ascending track seems to be 100 degrees which seems to be the satellite heading angle from east counter clock wise. This angle is not exactly what we should add to the static layer. The layers in the static layer are supposed to describe the los unit vector from target to the platform. We should either provide los unit vector (target to sensor) components in east north and up directions (three layers) or incidence angle and azimuth angle of the los vector (target to the sensor vector). The azimuth angle may be clockwise from north. 

If we want to include los unit vector east north and up components, then those parameters should be returned from running topo. If incidence and azimuth angle of LOS is desired, then topo needs to be fixed as discussed [here](https://github-fn.jpl.nasa.gov/isce-3/isce/issues/1370) .

### What did you expect?

I expected to see the azimuth angle of the LOS vector (target to satellite vector).

### Reproducible steps

```bash
Produce static layers for a burst.
```

**Comment by hfattahi** [comment]
This issue affects the downstream workflows in mintpy as discussed [here](https://github.com/insarlab/MintPy/discussions/1016)

**Comment by vbrancat** [comment]
Addressing this in #181

**Comment by vbrancat** [comment]
This issue has been addressed by including the East/North LOS unit vectors in CSLC-S1 static layers
