### ISSUE TITLE
How can I make a burst-db-database?

### ISSUE THREAD

**Issue by HyeokJaeKiM** [opera-adt/COMPASS#217]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

I want to make a CSLC image in my interest region

so I try to make " s1_cslc_geo.yaml "   ---picture 1

but I got a error. I guess the reason is due to burst_database_file missing  --picture 2

So I try to do " burst_db " that you gave us. I finished doing " opera-db-create " --picture3

but I don't know how to use them files that I made after doing " opera-db-create "

Could you answer me  ① how to make a " burst_database_file "
and If my way is correct, ② how to make a "burst_database_file in " burst_db in github "

Thanks for reading my question sir!
![1](https://github.com/opera-adt/COMPASS/assets/141599398/64b79d7c-e0e9-4ec5-bb42-746437148dec)
![2](https://github.com/opera-adt/COMPASS/assets/141599398/472de183-1be5-4a7b-b556-2d8454508b25)
![3](https://github.com/opera-adt/COMPASS/assets/141599398/36ffe65f-ce0e-4877-9939-2afc3ea957bf)

### Describe the feature request

I need or want [...]

**Comment by scottstanie** [comment]
You need to put the file location in that part of the YAML. I can't say for sure this is right from your screen shot, but I think that line should read
```yaml
burst_database_file: /home/burst_db/opera-burst-bbox-only.sqlite3
```

The other alternative is to use [sweets](https://github.com/isce-framework/sweets) to run COMPASS, since it will download the sqlite file and make the YAMLs for you

**Comment by HyeokJaeKiM** [comment]
Thanks you sir!

After adding " burst_database_file:
/home/burst_db/opera-burst-bbox-only.sqlite3 ", it works

but there is another error -- picture 4

I think that error is result from my data ( S1 data, DEM etc ..)

So Can I get some sample data for testing my code

such as Sentinel-1 image, DEM, Orbit file

I must make a CSLC image. If you can, would you help me..?

Thank you for reading my asking consistently

2024년 1월 22일 (월) 오전 10:16, Scott Staniewicz ***@***.***>님이 작성:

**Comment by scottstanie** [comment]
I can't see the pictures you've posted (but if you repost, please paste the text rather than a picture of the screen), but for now I think I'll close this as having essentially the same problem as #216 - more clarification on running locally.

The quickest method to have some working run of COMPASS would be to follow https://github.com/isce-framework/sweets#usage . The main difference between that an the OPERA production data is the lack of ionospheric tec files in the COMPASS configuration.

**Comment by HyeokJaeKiM** [comment]
Hello sir

I run this " (isce3) ***@***.***:~$ s1_cslc.py --grid geo
/home/hyeokjaekim/data/s1_cslc_geo.yaml "

but I got this message

*Warning: Could not find a 100% match in EPSG data base for wkt: *
*BOUNDCRS[*
*    SOURCECRS[*
*        PROJCRS["Transverse Mercator",*
*            BASEGEOGCRS["GRS80 ELLIPSOID",*
*                DATUM["GRS80 ELLIPSOID",*
*                    ELLIPSOID["GRS 1980",6378137,298.257222101004,*
*                        LENGTHUNIT["metre",1,*
*                            ID["EPSG",9001]]]],*
*                PRIMEM["Greenwich",0,*
*                    ANGLEUNIT["degree",0.0174532925199433,*
*                        ID["EPSG",9122]]]],*
*            CONVERSION["unnamed",*
*                METHOD["Transverse Mercator",*
*                    ID["EPSG",9807]],*
*                PARAMETER["Latitude of natural origin",38.0000000000001,*
*                    ANGLEUNIT["degree",0.0174532925199433],*
*                    ID["EPSG",8801]],*
*                PARAMETER["Longitude of natural origin",127,*
*                    ANGLEUNIT["degree",0.0174532925199433],*
*                    ID["EPSG",8802]],*
*                PARAMETER["Scale factor at natural origin",1,*
*                    SCALEUNIT["unity",1],*
*                    ID["EPSG",8805]],*
*                PARAMETER["False easting",200000,*
*                    LENGTHUNIT["metre",1],*
*                    ID["EPSG",8806]],*
*                PARAMETER["False northing",600000,*
*                    LENGTHUNIT["metre",1],*
*                    ID["EPSG",8807]]],*
*            CS[Cartesian,2],*
*                AXIS["easting",east,*
*                    ORDER[1],*
*                    LENGTHUNIT["metre",1,*
*                        ID["EPSG",9001]]],*
*                AXIS["northing",north,*
*                    ORDER[2],*
*                    LENGTHUNIT["metre",1,*
*                        ID["EPSG",9001]]]]],*
*    TARGETCRS[*
*        GEOGCRS["WGS 84",*
*            DATUM["World Geodetic System 1984",*
*                ELLIPSOID["WGS 84",6378137,298.257223563,*
*                    LENGTHUNIT["metre",1]]],*
*            PRIMEM["Greenwich",0,*
*                ANGLEUNIT["degree",0.0174532925199433]],*
*            CS[ellipsoidal,2],*
*                AXIS["latitude",north,*
*                    ORDER[1],*
*                    ANGLEUNIT["degree",0.0174532925199433]],*
*                AXIS["longitude",east,*
*                    ORDER[2],*
*                    ANGLEUNIT["degree",0.0174532925199433]],*
*            ID["EPSG",4326]]],*
*    ABRIDGEDTRANSFORMATION["Transformation from GRS80 ELLIPSOID to WGS84",*
*        METHOD["Position Vector transformation (geog2D domain)",*
*            ID["EPSG",9606]],*
*        PARAMETER["X-axis translation",0,*
*            ID["EPSG",8605]],*
*        PARAMETER["Y-axis translation",0,*
*            ID["EPSG",8606]],*
*        PARAMETER["Z-axis translation",0,*
*            ID["EPSG",8607]],*
*        PARAMETER["X-axis rotation",0,*
*            ID["EPSG",8608]],*
*        PARAMETER["Y-axis rotation",0,*
*            ID["EPSG",8609]],*
*        PARAMETER["Z-axis rotation",0,*
*            ID["EPSG",8610]],*
*        PARAMETER["Scale difference",1,*
*            ID["EPSG",8611]]]]*


*RuntimeError: Error in file
/home/conda/feedstock_root/build_artifacts/isce3_1705520530246/work/cxx/isce3/core/Projections.cpp,
line 389, function isce3::core::ProjectionBase*
isce3::core::createProj(int): Unknown EPSG code (in factory): 5186*

I guess this message says that some my data's EPSG is 5186 but isce3 can
not support 5186 EPSG

but I can not understand why my data is EPSG 5186? I found my data is EPSG
4326!

*So can I get some sample data such as sentinel-1, dem, orbit file,
burstdatabse if you can?*

*I just want to know that problem is result from my code or my data*

*Please answer my quetion!*

*Thank you sir*


2024년 1월 23일 (화) 오전 2:53, Scott Staniewicz ***@***.***>님이 작성:

**Comment by scottstanie** [comment]
I believe your DEM isn't correctly formed, but we'd need more information about what you did to figure that you.
