### ISSUE TITLE
Docker: 

### ISSUE THREAD

**Issue by hfattahi** [opera-adt/COMPASS#25]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

The delivery to SDS will be a docker image. 

### Describe the feature request

We need a recipe to create a Docker image. In this recipe isce3 should be installed from conda package.

**Comment by seongsujeong** [comment]
On it. So the recipe will install the dependencies using conda, and builds ISCE3 from source. Would it make sense?

**Comment by hfattahi** [comment]
@rtburns-jpl started updating isce3 conda package. I think we should use that one and avoid building from source.

**Comment by hfattahi** [comment]
The conda package seems to have been updated: https://anaconda.org/conda-forge/isce3

**Comment by seongsujeong** [comment]
Closing this issue ticket as the PR #30 has merged into the main branch.
