### ISSUE TITLE
[Bug]: nan value in array causes snaphu to fail

### ISSUE THREAD

**Issue by scottstanie** [opera-adt/COMPASS#50]
### Checked for duplicates

Yes - I have checked

### Describe the bug

The current nodata value of nan does not agree with SNAHPHU. It causes the error `NaN or infinity found in input float data`:
```
ValueError: Error in file /home/conda/feedstock_root/build_artifacts/isce3_1657045316397/work/cxx/isce3/unwrap/snaphu/snaphu_io.cpp, line 2087, function int isce3::unwrap::ReadInputFile(isce3::unwrap::infileT*, isce3::unwrap::Array2D<float>*, isce3::unwrap::Array2D<float>*, isce3::unwrap::Array2D<short int>*, long int, long int, isce3::unwrap::paramT*, isce3::unwrap::tileparamT*): NaN or infinity found in input float data
```

This is coming from a check that snaphu does on input phase to immediately abort upon seeing a nan or an infinity:

https://github.com/isce-framework/isce3/blob/49f18304a8fcba33dbf33347a64b7f89117cdcf6/cxx/isce3/unwrap/snaphu/snaphu_io.cpp#L2083-L2089
https://github.com/isce-framework/isce3/blob/49f18304a8fcba33dbf33347a64b7f89117cdcf6/cxx/isce3/unwrap/snaphu/snaphu_util.cpp#L464-L476

### What did you expect?

I expected SNAPHU to respect a 0 correlation mask, but it doesn't seem to matter if I change it to ` corr = np.ones((w, l), dtype='float32'); corr[0] = 0; corr_raster = isce3.io.gdal.Raster(corr)`. The check right now is hardcoded to always fail upon a nan.

### Reproducible steps

```bash
from isce3.unwrap import snaphu
import isce3.io

w = l = 5

unw_raster = isce3.io.gdal.Raster("unw.tif", w, l, np.float32, "GTiff")
ccl_raster = isce3.io.gdal.Raster("ccl.tif", w, l, np.uint32, "GTiff")

igram = np.ones((w, l), dtype='complex64')
igram[0] = np.nan
igram_raster = isce3.io.gdal.Raster(igram)

corr_raster = isce3.io.gdal.Raster(np.ones((w, l), dtype='float32'))

snaphu.unwrap( unw_raster, ccl_raster, igram_raster, corr_raster)
```

### Environment

```bash
In [27]: %load_ext watermark

In [28]: %watermark
Last updated: 2022-08-21T14:04:50.917644-07:00

Python implementation: CPython
Python version       : 3.10.5
IPython version      : 8.4.0

Compiler    : GCC 10.3.0
OS          : Linux
Release     : 3.10.0-1160.59.1.el7.x86_64
Machine     : x86_64
Processor   : x86_64
CPU cores   : 224
Architecture: 64bit
```

**Comment by vbrancat** [comment]
If I am not wrong, we have the capability of changing the `nodata` value in our CSLC core module, please @LiangJYu can you confirm that? 

If not `nan+jnan`, what would be a plausible `nodata` value for the displacement workflow?
Also, just out of curiosity, have you tried to give SNAPHU a mask with the `nodata` value locations?

**Comment by LiangJYu** [comment]
We currently do not have the ability to change the `nodata` value. Updating CSLC to pass to replace the [default `nan + j * nan`](https://github.com/isce-framework/isce3/blob/04b17713adec76348ab63718895cb8eca4912d25/python/extensions/pybind_isce3/geocode/GeocodeSlc.cpp#L50-L52) in `isce3.geocode.geocode_slc` shouldn't be difficult.

**Comment by scottstanie** [comment]
@vbrancat It does seem like the byte mask should ignore the nans, and perhaps we could change the SNAPHU code to make that work; as it stands, SNAPHU first runs first runs `ReadInputFile` which calls `ValidDataArray` to check for nans (and fails if there are nans), then runs runs `ReadByteMask` *after* that point :\

**Comment by scottstanie** [comment]
I'll say that my current opinion is this: If we can't think of a better option overall for a NoData value (and there's really nothing wrong for most cases with `nan` as long as you say "The nodata value is `nan`"), we can work around it. It shouldn't be a big cost to make a temporary file with `nan`s replaced by 0s if we call SNAPHU

**Comment by scottstanie** [comment]
Closing this because it can be handled by tophu/other unwrapping scripts, which have to check for multiple unwrapper-specific quirks anyway
