### ISSUE TITLE
[Bug]: Strange GSLC produced using s1_geocode_stack.py over Rosamond for descending track 071

### ISSUE THREAD

**Issue by gracebato** [opera-adt/COMPASS#66]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

I've been testing the COMPASS software and have been processing both the descending (D071) and ascending (A064) tracks over Rosamond, CA. I noticed some strange output with D071 (`burst_id=151224`) but not in A064 (`burst_id= 135523`). Increasing the stack size or using a different `--start-date` and/or `--end-date` did not help with the output GSLC for the descending track.

**A064**
![output_A064](https://user-images.githubusercontent.com/47398144/203462646-58fa4f8e-cea3-4950-814f-d84c3852a5b4.png)

D071
![output_D071](https://user-images.githubusercontent.com/47398144/203462719-e1ebc7a2-f34d-414a-9d9d-bc8b77cb7874.png)

### What did you expect?

The output GSLC should be similar to the burst_id coverage/track (e.g. A064 output). Bleeding pixels or cut-off area are not expected.

### Reproducible steps

```bash
> s1_geocode_stack.py -s slcs -d glo_30.dem.wgs84 --burst-db-file BURST_MAP/burst_map_bbox_only.sqlite3 -o COMPASS_TEST/D071/stack/orbits --burst-id t071_151224_iw2 -w COMPASS_TEST/D071/stack --metadata --start-date 20190101

> sh run_files/run_20190105_t071_151224_iw2.sh
```

### Environment

```bash
- COMPASS v0.1.2 2022-07-21
- CentOS Linux release 7.9.2009 (Core)
```

**Comment by gracebato** [comment]
I processed the same track (D071), using `s1_cslc.py` instead of `s1_geocode_stack.py` and it seems the former works well. 

**D071**
![output_D071_20210106_s1_cslc](https://user-images.githubusercontent.com/47398144/204659919-f3f963da-0480-450d-b41b-293e83f1c856.png)

**Comment by scottstanie** [comment]
we can check on this to make sure it's been resolved, but it looks similar to issues that me and @mirzaees had while running multiple geocodings in a row. It was either something in isce3 version 0.8.0 (and we released a new one available on conda this weeke https://github.com/isce-framework/isce3/releases/tag/v0.9.0 ) or it was related to the COMPASS-level issue i ran into here https://github.com/opera-adt/COMPASS/blob/main/src/compass/s1_geocode_slc.py#L50-L52

**Comment by vbrancat** [comment]
Closing as it has been resolved with  https://github.com/isce-framework/isce3/releases/tag/v0.9.0
