### ISSUE TITLE
[change the main dataset name]: 

### ISSUE THREAD

**Issue by hfattahi** [opera-adt/COMPASS#73]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

the main dataset is named "complex_backscatter" and that seems too long and not fully represnetative of the content. The developer team agrees to change to "slc"

### Describe the feature request

rename "complex_backscatter" to "slc" in HDF5

**Comment by yunjunz** [comment]
Close this issue as it has been implemented in #74 by @LiangJYu.
