### ISSUE TITLE
[New Feature]: Geocoded LUT for calibration

### ISSUE THREAD

**Issue by seongsujeong** [opera-adt/COMPASS#76]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

Sentinel1 SAFE file includes calibration annotation for `sigmaNaught`,  `betaNaught`, and `gamma`. COMPASS output stores those information in `/science/SENTINEL1/CSLC/corrections/calibration`, but they are in range coordinate. Because of the difference of the coordinate system, it is not straightforward to utilize the correction information to the product to apply it. Therefore we need a LUT in geogrid for the correction. Its resolution will be way much coarser than the geocoded SLC.

The spacing for the geocoded LUT is TBD. It needs to be decided after the analysis to find the optimal value.
The spacing of the LUT in range direction is 40pixels. That is approximately 155m in far ground range.

### Describe the feature request

We need a geocoded LUT into output `.h5` file for radiometric correction.

**Comment by vbrancat** [comment]
Closing since the corresponding PR has been merged
