### ISSUE TITLE
Add `pandas` into `requirements.txt`

### ISSUE THREAD

**Issue by seongsujeong** [opera-adt/COMPASS#81]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

`s1_geocode_stack.py` from PR #53 (merged as of Oct 2022) imports `pandas`
This is a reminder that we need to add this module in `requirements.txt`

### What did you expect?

We need to add `pandas` into `requirements.txt` in order to use `s1_geocode_stack.py`

### Reproducible steps

```bash
1.
2.
3.
...
```

### Environment

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```

**Comment by vbrancat** [comment]
Addresed by #88
