### ISSUE TITLE
[Bug]: units not showing up in CSLC metadata

### ISSUE THREAD

**Issue by LiangJYu** [opera-adt/COMPASS#83]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

@scottstanie commented on the lack of units in the correction meta data [here](https://github.com/opera-adt/COMPASS/pull/78/files#r1065296026).

### What did you expect?

I expected units.

### Reproducible steps

```bash
1.
2.
3.
...
```

### Environment

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```

**Comment by vbrancat** [comment]
Addressed this in #78
