### ISSUE TITLE
[Bug]: segfault in s1_geocode_slc with split_spectrum and dual/cross_pol

### ISSUE THREAD

**Issue by LiangJYu** [opera-adt/COMPASS#86]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

When s1_geocode_slc is ran with `split_spectrum` enabled and polarization set to either `dual_pol` or `cross_pol` a segfault occurs.

### What did you expect?

I expected it to not segfault

### Reproducible steps

```bash
1. enable split spectrum in runconfig
2. set polarization to dual_pol or cross_pol in runconfig
3. run s1_geocode_slc with runconfig modified as described above
```

### Environment

```bash
- PR#84
```

**Comment by vbrancat** [comment]
@LiangJYu yes, when split-spectrum is enabled, we need to geocode all 3 SLCs (main, low, and side band). They should be allocated as separate layers inside the product (e.g. `VV_low_band,` `VV_high_band`). Also, most likely, when we have the `dual-pol `mode enabled, we do not want to split the spectrum for both polarizations but only for the co-pol channel.

**Comment by vbrancat** [comment]
Closing since we have removed the split-spectrum from CSLC generation
